http.port=${PBS_HTTP_PORT}
server.port=${PBS_SERVER_PORT}

server.servlet.session.timeout=360m
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${PBS_DB_IP}:${PBS_DB_PORT}/${PBS_DB_NAME}?reWriteBatchedInserts=true
spring.datasource.username=${PBS_DB_USERNAME}
spring.datasource.password=${PBS_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.event.merge.entity_copy_observer=allow
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true