http.port=${AUTOMATIX_HTTP_PORT}
server.port=${AUTOMATIX_SERVER_PORT}

server.servlet.session.timeout=360m
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${AUTOMATIX_DB_IP}:${AUTOMATIX_DB_PORT}/${AUTOMATIX_DB_NAME}?reWriteBatchedInserts=true
spring.datasource.username=${AUTOMATIX_DB_USERNAME}
spring.datasource.password=${AUTOMATIX_DB_PASSWORD}

#spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.event.merge.entity_copy_observer=allow
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true